---
title: C6242
description: Descreve o C6242 de aviso do compilador C/C++ da Microsoft.
ms.date: 08/24/2020
ms.topic: reference
f1_keywords:
- C6242
helpviewer_keywords:
- C6242
ms.assetid: 523d46ce-8370-434c-a752-2e3a18cca9a5
ms.openlocfilehash: 57bfc8f6ed009238375e3e7e810909e09bd5df8b
ms.sourcegitcommit: a1676bf6caae05ecd698f26ed80c08828722b237
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 09/29/2020
ms.locfileid: "91498977"
---
# <a name="c6242"></a>C6242

> aviso C6242: um salto para fora desse bloco try força o desenrolamento local. Incorre em penalidade de desempenho grave

Esse aviso indica que uma instrução de salto faz com que o fluxo de controle deixe o bloco protegido de um `try-finally` diferente de por passagem.

Deixar o bloco protegido de `try-finally` outro do que passar da última instrução exige que o desenrolamento local ocorra. O desenrolamento local normalmente requer aproximadamente 1000 instruções de máquina, portanto, é prejudicial ao desempenho.

Use **`__leave`** para sair do bloco protegido de uma tentativa-finally.

## <a name="example"></a>Exemplo

O código a seguir gera este aviso:

```cpp
#include <malloc.h>
void DoSomething(char *p); // function can throw exception

int f( )
{
   char *ptr = 0;
   __try
   {
      ptr = (char*) malloc(10);
      if ( !ptr )
      {
         return 0;   //Warning: 6242
      }
      DoSomething( ptr );
   }
   __finally
   {
      free( ptr );
   }
   return 1;
}
```

Para corrigir esse aviso, use **`__leave`** conforme mostrado no código a seguir:

```cpp
#include <malloc.h>
void DoSomething(char *p);
int f()
{
   char *ptr = 0;
   int retVal = 0;

   __try
   {
      ptr = (char *) malloc(10);
      if ( !ptr )
      {
         retVal = 0;
         __leave;   //No warning
      }
      DoSomething( ptr );
      retVal = 1;
   }
   __finally
   {
      free( ptr );
   }

   return retVal;
}
```

O uso de `malloc` e `free` tem muitas armadilhas em termos de vazamentos de memória e exceções. Para evitar esses tipos de vazamentos e problemas de exceção, use os mecanismos fornecidos pela biblioteca padrão do C++. Isso inclui [`shared_ptr`](../standard-library/shared-ptr-class.md) , [`unique_ptr`](../standard-library/unique-ptr-class.md) e [`vector`](../standard-library/vector.md) . Para obter mais informações, consulte [apontadores inteligentes](../cpp/smart-pointers-modern-cpp.md) e a [biblioteca padrão C++](../standard-library/cpp-standard-library-reference.md).

## <a name="see-also"></a>Consulte também

[`try-except` privacidade](../cpp/try-except-statement.md)\
[`try-finally` privacidade](../cpp/try-finally-statement.md)
